import {
  FaHtml5,
  FaCss3Alt,
  FaReact,
  FaNodeJs,
  FaGithub,
  FaJava,
  FaPython,
  FaBootstrap,
  FaDocker,
  FaGitAlt
} from "react-icons/fa";
import {
  SiMongodb,
  SiTailwindcss,
  SiJavascript,
  SiTypescript,
  SiExpress,
  SiNextdotjs,
  SiChakraui,
  SiDjango,
  SiRedux,
  SiReactrouter,
  SiPostgresql,
  SiRedis,
  SiSelenium,
  SiGithubactions,
  SiFastapi,
  SiLangchain,
  SiCucumber,
} from "react-icons/si";
import { IoLogoFirebase } from "react-icons/io5";
import { DiMysql } from "react-icons/di";
import { TbApi } from "react-icons/tb";

export const skills = [
  { name: "HTML5", icon: FaHtml5 },
  { name: "CSS3", icon: FaCss3Alt },
  { name: "JavaScript", icon: SiJavascript },
  { name: "TypeScript", icon: SiTypescript },
  { name: "React.js", icon: FaReact },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "Node.js", icon: FaNodeJs },
  { name: "Express.js", icon: SiExpress },
  { name: "FastAPI", icon: SiFastapi },
  { name: "REST APIs", icon: TbApi },
  { name: "MongoDB", icon: SiMongodb },
  { name: "MySQL", icon: DiMysql },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "Redis", icon: SiRedis },
  { name: "Firebase", icon: IoLogoFirebase },
  { name: "Docker", icon: FaDocker },
  { name: "Git", icon: FaGitAlt },
  { name: "GitHub Actions", icon: SiGithubactions },
  { name: "GitHub", icon: FaGithub },
  { name: "Selenium", icon: SiSelenium },
  { name: "Cucumber", icon: SiCucumber },
  { name: "LangChain", icon: SiLangchain },
  { name: "Python", icon: FaPython },
  { name: "Java", icon: FaJava },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "Redux", icon: SiRedux },
  { name: "Django", icon: SiDjango },
  { name: "Bootstrap", icon: FaBootstrap },
  { name: "Chakra UI", icon: SiChakraui },
  { name: "React Router", icon: SiReactrouter },
];
